// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4G_Cdeysfq2zXOUermX3dAs02d_ZrWYY',
    appId: '1:47507295525:web:b50f75e6a43e6c1af51ecc',
    messagingSenderId: '47507295525',
    projectId: 'guruh2-9e553',
    authDomain: 'guruh2-9e553.firebaseapp.com',
    storageBucket: 'guruh2-9e553.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvfdZowQNjIdEsB8_yPmySt1xv_Qlluyg',
    appId: '1:47507295525:android:eaed2b38482a4237f51ecc',
    messagingSenderId: '47507295525',
    projectId: 'guruh2-9e553',
    storageBucket: 'guruh2-9e553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb4_jpEJrsHwrax3aEtxpeQtNbOkPQA4M',
    appId: '1:47507295525:ios:9f216995290e8a04f51ecc',
    messagingSenderId: '47507295525',
    projectId: 'guruh2-9e553',
    storageBucket: 'guruh2-9e553.firebasestorage.app',
    iosBundleId: 'com.example.guruh2',
  );
}
